---
name: Tests

on:
  push:
    branches: [master]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.x']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pip3 install pylint mypy coverage

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run linters
        run: |
          pylint --errors-only full_offline_backup_for_todoist
          mypy --strict -m full_offline_backup_for_todoist

      - name: Run tests
        run: coverage run -m unittest && coverage lcov

      - name: Upload coverage report
        if: ${{ matrix.python-version == '3.x' }}
        uses: coverallsapp/github-action@v2.3.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          files: coverage.lcov
